[package]
name = "nostrfeed"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
nostr-sdk = { version = "0.37.0", features = ["nip04"] }
serde = "1.0.216"
tokio = "1.42.0"
toml = "0.8.19"
