[package]
name = "MN_DVM"
about = "A DVM for highlighting the MN nostr community"
lnurl = "bravecheetah9@primal.net"
# If nsec isn't present, a new nsec will be generated
# DANGER: Do not commit your real nsec
nsec = "3bd0a7f5ab788d086dd2fea661916597ff1c251e028a25fcbaea2a3f531f08d5"
# Set to true internally after a 31990 is sent out
announced = false
# If random_id isn't present, a new rand id will be generated
random_id = "1x2vw03u6vp9jf5v9uh6"

[comms]
relays = [
    "wss://nostr.oxtr.dev",
    "wss://relay.damus.io",
    "wss://nostr.openchain.fr",
    "wss://relay.primal.net",
]
admins = [
    "npub1vhyr9c96vzfxhfxfysftkzv6pnp0je589t3e7s0xm9tqm34ghkdqwqeayv",
    "npub1jd3flna8yd8qy5ylzuxlgyuyqmsdaq7xslf0vcem09as4u78vvpslzs0cs",
]
npubs = [
    "npub1x2pcun7srmkycqdmc6y3ne7zt8cpn5nc5tcykh6q8utswe4nl5aslyjhqk",
    "npub1vhyr9c96vzfxhfxfysftkzv6pnp0je589t3e7s0xm9tqm34ghkdqwqeayv",
    "npub1q58hraynp4mupqcertys3gdp0e64yg2ccwyvhg7zu7483xcj2p4srxncdc",
    "npub16tekx03w0c5ydpmr72pl8m6h7xmvneevqjulrrsfrwmpefkf4s3q5cn4en",
    "npub1h9ldj0lymuktgczfmvgvpcv05gnxup9tgk995xvwc0h5rqdzzdps98qwuj",
    "npub1zswjq57t99f444z6485xtn0vfyjjfu8vqpnyj6uckuyem2446evqnxgc6x",
    "npub1erd0qsdgc80vpqjd70aafw0mx3qfyeqlc8whc3hy2ehxzxh4ddzs62e72c",
    "npub14d488egl5he3r4qy89psn23kz9sql5va8ec39rs7ltcas8ymr76sgk6evk",
    "npub1kw0qjutcah6c4sutjppl93m4cecs3ugnymllg34y6wjkahshy02safagdp",
    "npub1a6c3jcdj23ptzcuflek8a04f4hc2cdkat95pd6n3r8jjrwyzrw0q43lfrr",
    "npub1vlhlw55fk6z6sjuaf6sgjvlgetja46sjk2m36h3waaqgxwn5rc2shhf9x9",
]
